name: Run All Tests

on:
  push:
    branches: [main]

jobs:
  Test-on-Chrome:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code from the repository
      - name: Checkout GitCode
        uses: actions/checkout@v3.3.0

      # Set up Node.js environment and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose the Node.js version you are using (e.g., '16')

      # Install the project dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress Tests (after dependencies are installed)
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5.0.8
        with:
          record: true           # Set to 'true' to record the tests (if you have a Cypress Dashboard)
          parallel: true         # To run tests in parallel across multiple machines if applicable
          command: "npx cypress run"  # Command to run Cypress tests
